# Grafana Tempo Configuration for Jenkins Master-Pod Tracing
# =============================================================

# Enable Tempo for distributed tracing
tempo:
  # Storage configuration
  storage:
    trace:
      # Use local storage for development (change to S3/Azure Blob for production)
      backend: local
      local:
        path: /var/tempo/traces
      # Uncomment for Azure Blob Storage in production:
      # backend: azure
      # azure:
      #   storage_account_name: yourstorageaccount
      #   storage_account_key: yourkey
      #   container_name: tempo-traces

  # Tempo configuration
  config: |
    server:
      http_listen_port: 3200
      grpc_listen_port: 9095
      log_level: info

    distributor:
      receivers:
        jaeger:
          protocols:
            grpc:
              endpoint: 0.0.0.0:14250
            thrift_http:
              endpoint: 0.0.0.0:14268
            thrift_compact:
              endpoint: 0.0.0.0:6831
            thrift_binary:
              endpoint: 0.0.0.0:6832
        zipkin:
          endpoint: 0.0.0.0:9411
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
        opencensus:
          endpoint: 0.0.0.0:55678

    ingester:
      trace_idle_period: 10s
      max_block_bytes: 1_000_000
      max_block_duration: 5m

    compactor:
      compaction:
        compaction_window: 1h
        max_compaction_objects: 1000000
        block_retention: 1h
        compacted_block_retention: 10m

    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
        pool:
          max_workers: 100
          queue_depth: 10000

    query_frontend:
      search:
        duration_slo: 5s
        throughput_bytes_slo: 1.073741824e+09
      trace_by_id:
        duration_slo: 5s

    querier:
      max_concurrent_queries: 5

    usage_report:
      reporting_enabled: false

# Service configuration
service:
  type: ClusterIP
  port: 3200
  # Uncomment for LoadBalancer in production
  # type: LoadBalancer

# Enable persistence for traces
persistence:
  enabled: true
  size: 10Gi
  storageClassName: default

# Resource limits for Jenkins workload
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi

# Service Monitor for Prometheus integration
serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s

# Additional services for tracing protocols
serviceJaeger:
  enabled: true
  type: ClusterIP
  ports:
    - name: jaeger-grpc
      port: 14250
      targetPort: 14250
    - name: jaeger-thrift-http
      port: 14268
      targetPort: 14268
    - name: jaeger-thrift-compact
      port: 6831
      targetPort: 6831
      protocol: UDP
    - name: jaeger-thrift-binary
      port: 6832
      targetPort: 6832
      protocol: UDP

serviceZipkin:
  enabled: true
  type: ClusterIP
  port: 9411
  targetPort: 9411

serviceOtlp:
  enabled: true
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318

# Pod annotations for automatic instrumentation
podAnnotations:
  instrumentation.opentelemetry.io/inject-java: "true"
  instrumentation.opentelemetry.io/inject-python: "true"

# Node selector for spot vs regular nodes
nodeSelector:
  kubernetes.azure.com/scalesetpriority: Regular

# Tolerations for Jenkins workloads
tolerations:
  - key: "jenkins"
    operator: "Equal"
    value: "master"
    effect: "NoSchedule"

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  fsGroup: 10001
