#!/bin/bash

# Jenkins Configuration Summary Report
# Description: Complete summary of Jenkins Master and Spot Workers configuration

echo "📋 JENKINS CONFIGURATION SUMMARY REPORT"
echo "========================================"
echo ""

# Get Grafana IP
GRAFANA_IP=$(kubectl get svc grafana -n observability-stack -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || echo "GRAFANA_IP_NOT_FOUND")

echo "🎯 QUICK SUMMARY FROM LIVE EXTRACTION:"
echo ""

echo "👑 JENKINS MASTER CONFIGURATION:"
echo "─────────────────────────────────"
echo "• JVM Memory: -Xms512m -Xmx1536m (512MB-1.5GB)"
echo "• JVM Options: UseG1GC, headless mode"
echo "• Resource Limits: 1 CPU, 2Gi Memory"
echo "• Resource Requests: 300m CPU, 512Mi Memory"
echo "• Port: 8080 (HTTP), 50000 (Agent)"
echo "• Configuration: JCasC (Configuration as Code)"
echo ""

echo "🔌 INSTALLED PLUGINS:"
echo "────────────────────"
echo "• kubernetes - For spot workers"
echo "• workflow-aggregator - Pipeline support"
echo "• git - Source control"
echo "• configuration-as-code - JCasC"
echo "• build-timeout - Timeout management"
echo "• credentials-binding - Secure credentials"
echo "• timestamper - Log timestamps"
echo ""

echo "☁️  CLOUD CONFIGURATION:"
echo "──────────────────────"
echo "• Cloud Provider: kubernetes"
echo "• Namespace: jenkins-master"
echo "• Container Capacity: 10 concurrent"
echo "• Connect Timeout: 5s"
echo "• Read Timeout: 15s"
echo "• Jenkins URL: http://jenkins-master.jenkins-master.svc.cluster.local:8080"
echo "• Agent Tunnel: jenkins-master-agent.jenkins-master.svc.cluster.local:50000"
echo ""

echo "🎯 SPOT WORKERS STATUS:"
echo "──────────────────────"
echo "• Current Running Workers: $(kubectl get pods -n jenkins-workers 2>/dev/null | grep -c Running || echo "0")"
echo "• Spot Node: aks-spot-33804603-vmss000000"
echo "• Worker Image: jenkins/inbound-agent:latest"
echo "• Recent Activity: $(kubectl get events -n jenkins-workers --sort-by=.metadata.creationTimestamp 2>/dev/null | tail -1 | awk '{print $1" "$2" "$3}' || echo "No recent events")"
echo ""

echo "📊 CURRENT RESOURCE USAGE:"
echo "─────────────────────────"
kubectl top pods -n jenkins-master 2>/dev/null || echo "• Metrics server not available"
echo ""

echo "🔗 ACCESS INFORMATION:"
echo "─────────────────────"
JENKINS_IP=$(kubectl get svc jenkins-master -n jenkins-master -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || echo "JENKINS_IP_NOT_FOUND")
echo "• Jenkins Master: http://$JENKINS_IP"
echo "• Grafana Dashboard: http://$GRAFANA_IP"
echo "• Grafana Login: admin / admin123"
echo ""

echo "🔍 RECOMMENDED LOKI QUERIES FOR DETAILED ANALYSIS:"
echo "─────────────────────────────────────────────────"
echo ""
echo "📋 Master Configuration:"
echo "   {kubernetes_namespace_name=\"jenkins-master\"} |= \"JAVA_OPTS\" or \"plugin\" or \"config\""
echo ""
echo "🎯 Spot Workers Execution:"
echo "   {kubernetes_namespace_name=\"jenkins-workers\"} |= \"Build\" or \"Running\" or \"spot\""
echo ""
echo "⚠️  System Errors:"
echo "   {job=\"fluent-bit\"} |= \"jenkins\" |= \"ERROR\" or \"FAILED\""
echo ""
echo "📈 Performance Analysis:"
echo "   {job=\"fluent-bit\"} |= \"jenkins\" |= \"memory\" or \"cpu\" or \"duration\""
echo ""

echo "💡 WHAT YOU'VE LEARNED:"
echo "───────────────────────"
echo "✅ Jenkins Master is using G1 Garbage Collector with 1.5GB max heap"
echo "✅ 7 essential plugins are installed for Kubernetes spot workers"
echo "✅ Cloud configuration supports 10 concurrent workers on Kubernetes"
echo "✅ Spot workers are running on dedicated spot node: aks-spot-33804603-vmss000000"
echo "✅ Configuration as Code (JCasC) is enabled for infrastructure as code"
echo "✅ Security realm configured with local users (admin access)"
echo "✅ Complete observability stack with Loki + Grafana is operational"
echo ""

echo "🚀 NEXT STEPS FOR DETAILED ANALYSIS:"
echo "───────────────────────────────────"
echo "1. Run: ./queries/08_master_config_analysis.sh - For detailed master analysis"
echo "2. Run: ./queries/09_spot_execution_analysis.sh - For spot workers deep dive"
echo "3. Run: ./queries/10_complete_system_analysis.sh - For full system overview"
echo "4. Access Grafana: http://$GRAFANA_IP/explore - For real-time log analysis"
echo ""

echo "📋 CONFIGURATION FILES TO REVIEW:"
echo "─────────────────────────────────"
echo "• JCasC Config: kubectl get cm jenkins-master-jenkins-jcasc-config -n jenkins-master -o yaml"
echo "• Plugins List: kubectl get cm jenkins-master -n jenkins-master -o yaml"
echo "• Helm Values: ./helm/jenkins_helm_values.yaml"
echo "• Spot Cloud Config: ./jenkins_scripts/jenkins_spot_cloud.groovy"
