adminUser: admin
adminPassword: admin123

# Disable auto-generation of admin credentials
admin:
  existingSecret: ""
  userKey: ""
  passwordKey: ""

service:
  type: LoadBalancer
  port: 80

persistence:
  enabled: true
  size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector:
  nodepool: regular

tolerations:
  - key: "nodepool"
    operator: "Equal"
    value: "regular"
    effect: "NoSchedule"

env:
  GF_EXPLORE_ENABLED: true
  GF_LOG_LEVEL: info


