adminUser: admin
adminPassword: admin123

# Disable auto-generation of admin credentials
admin:
  existingSecret: ""
  userKey: ""
  passwordKey: ""

service:
  type: LoadBalancer
  port: 80

persistence:
  enabled: true
  size: 5Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      isDefault: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Programar en nodos regulares (como Loki)
nodeSelector:
  nodepool: regular

tolerations:
  - key: "nodepool"
    operator: "Equal"
    value: "regular"
    effect: "NoSchedule"

env:
  GF_EXPLORE_ENABLED: true
  GF_LOG_LEVEL: info


